In [1]:
import pandas as pd
import dec1
import datetime
from epw import epw

In [2]:
meteo_df=pd.read_csv('/home/ict4bd/Residential_oslo/weather_data/notmod_epw/IOSLOOSL9_2018.epw',index_col='Date_Time',parse_dates=[0,])
meteo_df.head()

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2018-01-01 01:00:00,1.000000,0.722222,98.0,45.0,0.000000,0.000000,98397.16,0.0,0.0,0.0,0.0
2018-01-01 01:10:00,1.000000,0.722222,98.0,45.0,0.000000,0.000000,98295.58,0.0,0.0,0.0,0.0
2018-01-01 01:20:00,1.000000,0.722222,98.0,45.0,0.000000,0.000000,98295.58,0.0,0.0,0.0,0.0
2018-01-01 01:30:00,1.000000,0.722222,98.0,22.5,0.894055,0.894055,98295.58,0.0,0.0,0.0,0.0
2018-01-01 01:40:00,1.111111,0.833333,98.0,270.0,0.894055,1.341082,98295.58,0.0,0.0,0.0,0.0

In [3]:
meteo=meteo_df.resample('H').mean().interpolate()
meteo.head()

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2018-01-01 01:00:00,1.037037,0.759259,98.0,93.75,0.447027,0.596036,98312.51,0.0,0.0,0.0,0.0
2018-01-01 02:00:00,1.138889,0.861111,98.0,112.50,0.894055,1.341082,98278.65,0.0,0.0,0.0,0.0
2018-01-01 03:00:00,1.763889,1.486111,98.0,123.75,0.894055,1.005811,98295.58,0.0,0.0,0.0,0.0
2018-01-01 04:00:00,1.955556,1.677778,98.0,144.00,0.000000,0.178811,98295.58,0.0,0.0,0.0,0.0
2018-01-01 05:00:00,2.138889,1.861111,98.0,78.75,0.447027,0.521532,98295.58,0.0,0.0,0.0,0.0

In [4]:
### Comment this line if year is not 2016
#meteo=meteo.drop(pd.date_range(start = '2016-02-29', end = '2016-03-01', freq='H', closed='left'))

In [5]:
file=pd.read_csv('/home/ict4bd/Residential_oslo/weather_data/radiation_data/2018/2018.csv', header=2, sep=',')
file=file.drop('Unnamed: 8', axis=1)

#meteo['Solar_W/m2']=file['GHI'].values
#meteo

In [6]:
meteo.columns
meteo

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2018-01-01 01:00:00,1.037037,0.759259,98.0,93.75,0.447027,0.596036,98312.51,0.0,0.000,0.0,0.0
2018-01-01 02:00:00,1.138889,0.861111,98.0,112.50,0.894055,1.341082,98278.65,0.0,0.000,0.0,0.0
2018-01-01 03:00:00,1.763889,1.486111,98.0,123.75,0.894055,1.005811,98295.58,0.0,0.000,0.0,0.0
2018-01-01 04:00:00,1.955556,1.677778,98.0,144.00,0.000000,0.178811,98295.58,0.0,0.000,0.0,0.0
2018-01-01 05:00:00,2.138889,1.861111,98.0,78.75,0.447027,0.521532,98295.58,0.0,0.000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 20:00:00,4.101852,3.814815,98.0,206.25,8.046491,8.046491,100699.64,0.0,2.032,0.0,0.0
2018-12-31 21:00:00,4.129630,3.851852,98.0,202.50,8.791536,8.791536,100513.41,0.0,2.032,0.0,0.0
2018-12-31 22:00:00,3.953704,3.675926,98.0,202.50,9.313068,9.313068,100225.60,0.0,2.032,0.0,0.0
2018-12-31 23:00:00,3.611111,3.314815,98.0,202.50,6.779914,7.301445,100005.51,0.0,2.032,0.0,0.0
2019-01-01 00:00:00,3.611111,3.314815,98.0,202.50,6.779914,7.301445,100005.51,0.0,2.032,0.0,0.0

In [7]:
#latitude = 59.912197  # latitude  N
#longitude = 10.752936  # longitude E
#elevation = 25  # meters above the sea

In [8]:
#rad=pd.DataFrame(meteo['Solar_W/m2'].values,index=meteo.index,columns=['ghi'])

In [9]:
#rad=dec1.main(rad,latitude,longitude,elevation)

In [10]:
data=epw()
data.read('NOR_Oslo.Fornebu.014880_IWEC.epw')

In [11]:
head=data.headers # this is a dictionary of the header information
print(head)

{'LOCATION': ['OSLO/FORNEBU', '-', 'NOR', 'IWEC Data', '014880', '59.90', '10.62', '1.0', '17.0'], 'DESIGN CONDITIONS': ['1', 'Climate Design Data 2009 ASHRAE Handbook', '', 'Heating', '1', '-17.2', '-14.5', '-19.9', '0.6', '-16', '-17', '0.8', '-12.9', '10.6', '5.4', '9.4', '4.2', '0.8', '0', 'Cooling', '7', '8.8', '26.8', '17.8', '25', '17', '23.2', '15.9', '19.2', '24.1', '18.2', '23.1', '17.1', '21.6', '3.2', '170', '17.7', '12.7', '20.6', '16.2', '11.5', '19.4', '15.2', '10.8', '18.5', '54.5', '23.7', '51.2', '23.1', '48.1', '21.3', '894', 'Extremes', '8.5', '7.3', '6.4', '24.3', '-18.7', '29.5', '4.2', '2.7', '-21.7', '31.4', '-24.2', '33', '-26.5', '34.5', '-29.6', '36.4'], 'TYPICAL/EXTREME PERIODS': ['6', 'Summer - Week Nearest Max Temperature For Period', 'Extreme', '7/27', '8/ 2', 'Summer - Week Nearest Average Temperature For Period', 'Typical', '8/ 3', '8/ 9', 'Winter - Week Nearest Min Temperature For Period', 'Extreme', '1/13', '1/19', 'Winter - Week Nearest Average Temperature For Period', 'Typical', '2/17', '2/23', 'Autumn - Week Nearest Average Temperature For Period', 'Typical', '10/27', '11/ 2', 'Spring - Week Nearest Average Temperature For Period', 'Typical', '3/29', '4/ 4'], 'GROUND TEMPERATURES': ['3', '.5', '', '', '', '-2.98', '-1.17', '2.35', '5.68', '11.99', '15.31', '16.23', '14.55', '10.66', '5.81', '1.03', '-2.12', '2', '', '', '', '-0.49', '-0.04', '1.96', '4.20', '9.05', '12.15', '13.69', '13.34', '11.13', '7.78', '4.01', '1.05', '4', '', '', '', '2.09', '1.78', '2.66', '3.93', '7.13', '9.53', '11.09', '11.47', '10.50', '8.53', '5.97', '3.66'], 'HOLIDAYS/DAYLIGHT SAVINGS': ['No', '0', '0', '0'], 'COMMENTS 1': ["IWEC- WMO#014880 - Europe -- Original Source Data (c) 2001 American Society of Heating, Refrigerating and Air-Conditioning Engineers (ASHRAE), Inc., Atlanta, GA, USA.  www.ashrae.org  All rights reserved as noted in the License Agreement and Additional Conditions. DISCLAIMER OF WARRANTIES: The data is provided 'as is' without warranty of any kind, either expressed or implied. The entire risk as to the quality and performance of the data is with you. In no event will ASHRAE or its contractors be liable to you for any damages, including without limitation any lost profits, lost savings, or other incidental or consequential damages arising out of the use or inability to use this data."], 'COMMENTS 2': [' -- Ground temps produced with a standard soil diffusivity of 2.3225760E-03 {m**2/day}'], 'DATA PERIODS': ['1', '1', 'Data', 'Sunday', ' 1/ 1', '12/31']}

In [12]:
df=data.dataframe.copy()  # this is pandas dataframe

In [13]:
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute',
       'Data Source and Uncertainty Flags', 'Dry Bulb Temperature',
       'Dew Point Temperature', 'Relative Humidity',
       'Atmospheric Station Pressure', 'Extraterrestrial Horizontal Radiation',
       'Extraterrestrial Direct Normal Radiation',
       'Horizontal Infrared Radiation Intensity',
       'Global Horizontal Radiation', 'Direct Normal Radiation',
       'Diffuse Horizontal Radiation', 'Global Horizontal Illuminance',
       'Direct Normal Illuminance', 'Diffuse Horizontal Illuminance',
       'Zenith Luminance', 'Wind Direction', 'Wind Speed', 'Total Sky Cover',
       'Opaque Sky Cover (used if Horizontal IR Intensity missing)',
       'Visibility', 'Ceiling Height', 'Present Weather Observation',
       'Present Weather Codes', 'Precipitable Water', 'Aerosol Optical Depth',
       'Snow Depth', 'Days Since Last Snowfall', 'Albedo',
       'Liquid Precipitation Depth', 'Liquid Precipitation Quantity'],
      dtype='object')

In [14]:
meteo.columns

Index(['Temperature_C', 'Dew_Point_C', 'Humidity', 'Wind', 'Speed_m/s',
       'Gust_m/s', 'Pressure_Pa', 'Precip_Rate_mm', 'Precip_Accum_mm', 'UV',
       'Solar_W/m2'],
      dtype='object')

In [15]:
#df.drop(df.tail(1).index,inplace=True) # drop last n rows
#df

In [16]:
df['Year'] = 2018
df

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,2018,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-10.6,-11.9,89,100600,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
1,2018,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-8.4,-9.6,90,100500,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
2,2018,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-6.8,-7.9,91,100400,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
3,2018,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-6.0,-7.0,92,100400,...,240,0,999099999,0,0.030,0,88,0.0,0.0,0.0
4,2018,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-5.6,-6.5,93,100400,...,240,9,999999999,0,0.030,0,88,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018,12,31,20,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-16.5,-18.4,84,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8756,2018,12,31,21,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-16.6,-18.4,84,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8757,2018,12,31,22,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-16.2,-18.0,85,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8758,2018,12,31,23,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-15.0,-16.6,86,100800,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8759,2018,12,31,24,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-13.0,-14.4,88,100700,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0

In [17]:
df['Dry Bulb Temperature']= meteo.Temperature_C.values

In [18]:
df['Dew Point Temperature']=meteo.Dew_Point_C.values

In [19]:
#df['Atmospheric Station Pressure']=meteo.Pressure_Pa

In [20]:
df['Relative Humidity']=meteo.Humidity.values

In [21]:
df['Global Horizontal Radiation']=file.GHI.values

In [22]:
df['Direct Normal Radiation']=file.DNI.values

In [23]:
df['Diffuse Horizontal Radiation']=file.DHI.values

In [24]:
df['Wind Direction']=meteo['Speed_m/s'].values

In [25]:
df['Wind Speed']=meteo['Speed_m/s'].values

In [26]:
df.head()

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,2018,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,1.037037,0.759259,98.0,100600,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
1,2018,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,1.138889,0.861111,98.0,100500,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
2,2018,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,1.763889,1.486111,98.0,100400,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
3,2018,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,1.955556,1.677778,98.0,100400,...,240,0,999099999,0,0.03,0,88,0.0,0.0,0.0
4,2018,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,2.138889,1.861111,98.0,100400,...,240,9,999999999,0,0.03,0,88,0.0,0.0,0.0

In [27]:
print(df[df['Global Horizontal Radiation']>0])

      Year  Month  Day  Hour  Minute  \
10    2018      1    1    11      60
11    2018      1    1    12      60
12    2018      1    1    13      60
13    2018      1    1    14      60
14    2018      1    1    15      60
...    ...    ...  ...   ...     ...
8746  2018     12   31    11      60
8747  2018     12   31    12      60
8748  2018     12   31    13      60
8749  2018     12   31    14      60
8750  2018     12   31    15      60

                 Data Source and Uncertainty Flags  Dry Bulb Temperature  \
10    B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              3.044444
11    B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              3.522222
12    A7A7E8E8*0G9G9G9I9I9I9I9A7A7A7A7A7A7*0E8*0*0              3.240741
13    B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              3.175926
14    B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              3.138889
...                                            ...                   ...
8746  B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              2.400000
8747  B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              2.592593
8748  A7A7E8E8*0G9G9G9I9I9I9I9A7A7A7A7A7A7*0E8*0*0              2.537037
8749  B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              2.518519
8750  B8C8E8B8*0H9H9H9I9I9I9I9*0B8B8B8B8*0*0E8*0*0              2.129630

      Dew Point Temperature  Relative Humidity  Atmospheric Station Pressure  \
10                 2.755556               98.0                        100400
11                 3.233333               98.0                        100500
12                 2.962963               98.0                        100500
13                 2.879630               98.0                        100500
14                 2.861111               98.0                        100500
...                     ...                ...                           ...
8746               2.122222               98.0                        100400
8747               2.314815               98.0                        100500
8748               2.259259               98.0                        100500
8749               2.240741               98.0                        100600
8750               1.851852               98.0                        100600

      ...  Ceiling Height  Present Weather Observation  Present Weather Codes  \
10    ...             120                            9              999999999
11    ...             120                            9              999999999
12    ...             210                            9              999999999
13    ...             210                            9              999999999
14    ...             210                            9              999999999
...   ...             ...                          ...                    ...
8746  ...             420                            9              999999999
8747  ...             420                            9              999999999
8748  ...             420                            9              999999999
8749  ...             420                            9              999999999
8750  ...             420                            9              999999999

      Precipitable Water  Aerosol Optical Depth  Snow Depth  \
10                     0                  0.030           8
11                     0                  0.030           8
12                     0                  0.030           8
13                     0                  0.030           8
14                     0                  0.030           8
...                  ...                    ...         ...
8746                   0                  0.032          34
8747                   0                  0.032          34
8748                   0                  0.032          34
8749                   0                  0.032          34
8750                   0                  0.032          34

      Days Since Last Snowfall  Albedo  Liquid Precipitation Depth  \
10                          88     0.0                         0.0
11                          88     0.0                         0.0
12                          88     0.0                         0.0
13                          88     0.0                         0.0
14                          88     0.0                         0.0
...                        ...     ...                         ...
8746                        88     0.0                         0.0
8747                        88     0.0                         0.0
8748                        88     0.0                         0.0
8749                        88     0.0                         0.0
8750                        88     0.0                         0.0

      Liquid Precipitation Quantity
10                              0.0
11                              0.0
12                              0.0
13                              0.0
14                              0.0
...                             ...
8746                            0.0
8747                            0.0
8748                            0.0
8749                            0.0
8750                            0.0

[4336 rows x 35 columns]

In [28]:
data.dataframe.head()

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,1991,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-10.6,-11.9,89,100600,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
1,1991,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-8.4,-9.6,90,100500,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
2,1991,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-6.8,-7.9,91,100400,...,77777,9,999999999,0,0.03,0,88,0.0,0.0,0.0
3,1991,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-6.0,-7.0,92,100400,...,240,0,999099999,0,0.03,0,88,0.0,0.0,0.0
4,1991,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-5.6,-6.5,93,100400,...,240,9,999999999,0,0.03,0,88,0.0,0.0,0.0

In [29]:
data.dataframe=df.copy()

In [30]:
data.headers['LOCATION']

['OSLO/FORNEBU',
 '-',
 'NOR',
 'IWEC Data',
 '014880',
 '59.90',
 '10.62',
 '1.0',
 '17.0']

In [31]:
data.write('final_2018_oslo_rad.epw')

In [32]:
data.dataframe

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,2018,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,1.037037,0.759259,98.0,100600,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
1,2018,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,1.138889,0.861111,98.0,100500,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
2,2018,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,1.763889,1.486111,98.0,100400,...,77777,9,999999999,0,0.030,0,88,0.0,0.0,0.0
3,2018,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,1.955556,1.677778,98.0,100400,...,240,0,999099999,0,0.030,0,88,0.0,0.0,0.0
4,2018,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,2.138889,1.861111,98.0,100400,...,240,9,999999999,0,0.030,0,88,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018,12,31,20,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,4.101852,3.814815,98.0,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8756,2018,12,31,21,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,4.129630,3.851852,98.0,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8757,2018,12,31,22,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,3.953704,3.675926,98.0,100900,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8758,2018,12,31,23,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,3.611111,3.314815,98.0,100800,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0
8759,2018,12,31,24,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,3.611111,3.314815,98.0,100700,...,22000,9,999999999,0,0.032,34,88,0.0,0.0,0.0